// Define the repository information in these attributes
:repository-owner: NitrofMtl



= DUE-ModbusDMA
:toc:
:icons: font

Drop-in replacement for https://github.com/arduino-libraries/ArduinoModbus[ArduinoModbus],
modified to work with https://github.com/NitrofMtl/DUERS485DMA[DUERS485DMA] on Arduino Due.

== Differences from the original ArduinoModbus

1. *Installation*
   - Install this library instead of the original ArduinoModbus.
   - Make sure to also install https://github.com/NitrofMtl/DUERS485DMA[DUERS485DMA].

2. *Include*
[source,cpp]
----
#include <ArduinoModbus-DUE-DMA.h>
----

3. *Class instantiation*
   - Unlike the original library, `ModbusRTUServerClass` and `ModbusRTUClientClass`
     are *not pre-instantiated*.  
   - Empty constructors were removed: you must pass your RS485 instance.  
   - Example:
[source,cpp]
----
ModbusRTUServerClass modbusServer(RS485);
ModbusRTUClientClass modbusClient(RS485);
----

4. *Everything else is the same*
   - API, examples, and functionality follow the official ArduinoModbus library.
   - See the official documentation: https://www.arduino.cc/en/ArduinoModbus/ArduinoModbus

== Examples
Check the `examples/` folder for usage.





= Modbus Library for Arduino =

image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml/badge.svg["Check Arduino status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/check-arduino.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml/badge.svg["Compile Examples status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/compile-examples.yml"]
image:https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml/badge.svg["Spell Check status", link="https://github.com/{repository-owner}/{repository-name}/actions/workflows/spell-check.yml"]

Use http://www.modbus.org/[Modbus] with your Arduino. 

Using TCP or RS485 shields, like the MKR 485 Shield. This library depends on the ArduinoRS485 library.

This library is based on https://github.com/stephane/libmodbus[libmodbus], modifications were made to the lower level RS485 and TCP layers to use Arduino Serial/RS485 and Client API's. Then an Arduino friendly API was added on top.

For more information about this library please visit us at
https://www.arduino.cc/en/ArduinoModbus/ArduinoModbus

== Useful resources ==

* https://en.wikipedia.org/wiki/Modbus[Modbus - Wikipedia]
* http://www.modbus.org/faq.php[Modbus FAQ]

== License ==

Copyright (c) 2018 Arduino SA. All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
